#!/bin/sh

uci -q batch <<-EOF >/dev/null
  delete network.wwan
  set network.wwan=interface
  set network.wwan.proto='dhcp'
  set network.wwan.ifname='wwan0'
  commit network
  
  set firewall.@zone[1].network='wan wan6 wwan'
  commit firewall

	delete ucitrack.@usbmodem[-1]
	add ucitrack usbmodem
	set ucitrack.@usbmodem[-1].init=usbmodem
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
